# Form implementation generated from reading ui file '/Users/pinxun/Documents/MindX/PTA/PTA09/TuanHy/python-app/ui/Home.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1080, 720)
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(-20, 0, 1111, 731))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA09/TuanHy/python-app/ui/../img/cỏ.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_5 = QtWidgets.QLabel(parent=Form)
        self.label_5.setGeometry(QtCore.QRect(0, 0, 1081, 101))
        self.label_5.setStyleSheet("background-color: rgba(255, 255, 255, 0.15); /* nền mờ */\n"
"border-radius: 12px;")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_8 = QtWidgets.QLabel(parent=Form)
        self.label_8.setGeometry(QtCore.QRect(50, 40, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(255, 255, 255)")
        self.label_8.setObjectName("label_8")
        self.btn_home = QtWidgets.QPushButton(parent=Form)
        self.btn_home.setGeometry(QtCore.QRect(620, 30, 191, 51))
        self.btn_home.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    background-color: transparent;\n"
"    border: 1px solid white;\n"
"    border-radius: 6px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 255, 255, 0.1); /* hiệu ứng hover nhẹ */\n"
"}")
        self.btn_home.setObjectName("btn_home")
        self.btn_profile = QtWidgets.QPushButton(parent=Form)
        self.btn_profile.setGeometry(QtCore.QRect(840, 30, 201, 51))
        self.btn_profile.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    color: #0b8f3c; /* xanh lá đậm */\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    padding: 6px 16px;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #e6ffe9; /* hiệu ứng hover nhẹ */\n"
"}")
        self.btn_profile.setObjectName("btn_profile")
        self.btn_list = QtWidgets.QPushButton(parent=Form)
        self.btn_list.setGeometry(QtCore.QRect(400, 30, 191, 51))
        self.btn_list.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    background-color: transparent;\n"
"    border: 1px solid white;\n"
"    border-radius: 6px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 255, 255, 0.1); /* hiệu ứng hover nhẹ */\n"
"}")
        self.btn_list.setObjectName("btn_list")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=Form)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 100, 1081, 621))
        self.stackedWidget.setStyleSheet("background-color: rgb(170, 255, 127);\n"
"background-color: transparent;")
        self.stackedWidget.setObjectName("stackedWidget")
        self.home = QtWidgets.QWidget()
        self.home.setObjectName("home")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.home)
        self.lineEdit_2.setGeometry(QtCore.QRect(530, 330, 311, 28))
        self.lineEdit_2.setStyleSheet("color: #888888;  /* Màu chữ xám nhạt */\n"
"    background-color: white;\n"
"    border: 1px solid #cccccc;  /* Viền mỏng */\n"
"    border-radius: 6px;\n"
"    padding: 4px 12px;\n"
"    font-size: 14px;")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_3 = QtWidgets.QLabel(parent=self.home)
        self.label_3.setGeometry(QtCore.QRect(200, 300, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(0, 0, 0)")
        self.label_3.setObjectName("label_3")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.home)
        self.lineEdit.setGeometry(QtCore.QRect(150, 330, 151, 28))
        self.lineEdit.setStyleSheet("color: #888888;  /* Màu chữ xám nhạt */\n"
"    background-color: white;\n"
"    border: 1px solid #cccccc;  /* Viền mỏng */\n"
"    border-radius: 6px;\n"
"    padding: 4px 12px;\n"
"    font-size: 14px;")
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(parent=self.home)
        self.label_2.setGeometry(QtCore.QRect(340, 150, 421, 61))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255)")
        self.label_2.setObjectName("label_2")
        self.label_10 = QtWidgets.QLabel(parent=self.home)
        self.label_10.setGeometry(QtCore.QRect(100, 290, 931, 111))
        self.label_10.setStyleSheet("background-color: white;\n"
"border-radius: 12px;")
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.btn_search = QtWidgets.QPushButton(parent=self.home)
        self.btn_search.setGeometry(QtCore.QRect(870, 300, 111, 91))
        self.btn_search.setStyleSheet("background-color: #007A3D;  /* Màu xanh đậm */\n"
"    border: none;               /* Không viền */\n"
"    border-radius: 10px;        /* Bo góc mềm */\n"
"    padding: 8px;")
        self.btn_search.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA09/TuanHy/python-app/ui/../img/magnifying-glass-solid.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_search.setIcon(icon)
        self.btn_search.setObjectName("btn_search")
        self.label_4 = QtWidgets.QLabel(parent=self.home)
        self.label_4.setGeometry(QtCore.QRect(650, 300, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(0, 0, 0)")
        self.label_4.setObjectName("label_4")
        self.label_9 = QtWidgets.QLabel(parent=self.home)
        self.label_9.setGeometry(QtCore.QRect(290, 70, 571, 61))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: rgb(255, 255, 255)")
        self.label_9.setObjectName("label_9")
        self.label_7 = QtWidgets.QLabel(parent=self.home)
        self.label_7.setGeometry(QtCore.QRect(380, 300, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(0, 0, 0)")
        self.label_7.setObjectName("label_7")
        self.lineEdit_3 = QtWidgets.QLineEdit(parent=self.home)
        self.lineEdit_3.setGeometry(QtCore.QRect(340, 330, 151, 28))
        self.lineEdit_3.setStyleSheet("color: #888888;  /* Màu chữ xám nhạt */\n"
"    background-color: white;\n"
"    border: 1px solid #cccccc;  /* Viền mỏng */\n"
"    border-radius: 6px;\n"
"    padding: 4px 12px;\n"
"    font-size: 14px;")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_2.raise_()
        self.label_10.raise_()
        self.btn_search.raise_()
        self.label_4.raise_()
        self.label_9.raise_()
        self.label_7.raise_()
        self.lineEdit_2.raise_()
        self.lineEdit_3.raise_()
        self.label_3.raise_()
        self.lineEdit.raise_()
        self.stackedWidget.addWidget(self.home)
        self.list = QtWidgets.QWidget()
        self.list.setObjectName("list")
        self.label_6 = QtWidgets.QLabel(parent=self.list)
        self.label_6.setGeometry(QtCore.QRect(20, 0, 351, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_6.setObjectName("label_6")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.list)
        self.scrollArea.setGeometry(QtCore.QRect(20, 40, 1040, 560))
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1038, 558))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.stackedWidget.addWidget(self.list)
        self.profile = QtWidgets.QWidget()
        self.profile.setObjectName("profile")
        self.label_11 = QtWidgets.QLabel(parent=self.profile)
        self.label_11.setGeometry(QtCore.QRect(230, -10, 691, 601))
        self.label_11.setStyleSheet("background-color: rgba(255, 255, 255, 50); /* Trong suốt */\n"
"            border: 1px solid rgba(255, 255, 255, 80);\n"
"            border-radius: 15px;")
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.label_22 = QtWidgets.QLabel(parent=self.profile)
        self.label_22.setGeometry(QtCore.QRect(250, 170, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        self.label_22.setFont(font)
        self.label_22.setStyleSheet("color: rgb(0, 0, 0)")
        self.label_22.setObjectName("label_22")
        self.txt_email = QtWidgets.QLineEdit(parent=self.profile)
        self.txt_email.setGeometry(QtCore.QRect(240, 220, 311, 41))
        self.txt_email.setStyleSheet("background-color: rgba(255, 255, 255, 50); /* Trong suốt */\n"
"            border: 1px solid rgba(255, 255, 255, 80);\n"
"            border-radius: 15px;")
        self.txt_email.setObjectName("txt_email")
        self.txt_name = QtWidgets.QLineEdit(parent=self.profile)
        self.txt_name.setGeometry(QtCore.QRect(600, 220, 311, 41))
        self.txt_name.setStyleSheet("background-color: rgba(255, 255, 255, 50); /* Trong suốt */\n"
"            border: 1px solid rgba(255, 255, 255, 80);\n"
"            border-radius: 15px;")
        self.txt_name.setObjectName("txt_name")
        self.label_23 = QtWidgets.QLabel(parent=self.profile)
        self.label_23.setGeometry(QtCore.QRect(240, 320, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("color: rgb(0, 0, 0)")
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(parent=self.profile)
        self.label_24.setGeometry(QtCore.QRect(610, 310, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        self.label_24.setFont(font)
        self.label_24.setStyleSheet("color: rgb(0, 0, 0)")
        self.label_24.setObjectName("label_24")
        self.label_29 = QtWidgets.QLabel(parent=self.profile)
        self.label_29.setGeometry(QtCore.QRect(610, 170, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        self.label_29.setFont(font)
        self.label_29.setStyleSheet("color: rgb(0, 0, 0)")
        self.label_29.setObjectName("label_29")
        self.txt_birthday = QtWidgets.QDateEdit(parent=self.profile)
        self.txt_birthday.setGeometry(QtCore.QRect(610, 350, 201, 41))
        self.txt_birthday.setStyleSheet("background-color: rgba(255, 255, 255, 50); /* Trong suốt */\n"
"color: rgb(0, 0, 0)")
        self.txt_birthday.setObjectName("txt_birthday")
        self.btn_save_account = QtWidgets.QPushButton(parent=self.profile)
        self.btn_save_account.setGeometry(QtCore.QRect(490, 450, 83, 29))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.btn_save_account.setFont(font)
        self.btn_save_account.setStyleSheet("background-color: rgb(170, 255, 0);\n"
"color: rgb(0, 0, 0)")
        self.btn_save_account.setObjectName("btn_save_account")
        self.txt_gender = QtWidgets.QComboBox(parent=self.profile)
        self.txt_gender.setGeometry(QtCore.QRect(240, 360, 171, 28))
        self.txt_gender.setObjectName("txt_gender")
        self.txt_gender.addItem("")
        self.txt_gender.addItem("")
        self.txt_gender.addItem("")
        self.txt_gender.addItem("")
        self.btn_avatar = QtWidgets.QPushButton(parent=self.profile)
        self.btn_avatar.setGeometry(QtCore.QRect(460, 0, 211, 161))
        self.btn_avatar.setStyleSheet("background-color: rgba(255, 255, 255, 50); /* Trong suốt */\n"
"            border: 1px solid rgba(255, 255, 255, 80);\n"
"            border-radius: 15px;")
        self.btn_avatar.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA09/TuanHy/python-app/ui/../img/user-solid.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_avatar.setIcon(icon1)
        self.btn_avatar.setIconSize(QtCore.QSize(130, 130))
        self.btn_avatar.setObjectName("btn_avatar")
        self.stackedWidget.addWidget(self.profile)
        self.detail = QtWidgets.QWidget()
        self.detail.setObjectName("detail")
        self.label_38 = QtWidgets.QLabel(parent=self.detail)
        self.label_38.setGeometry(QtCore.QRect(50, 30, 541, 571))
        self.label_38.setText("")
        self.label_38.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA09/TuanHy/python-app/ui/../img/san-bong-da-mini-tan-thoi-hoa-1_thumb_720.webp"))
        self.label_38.setScaledContents(True)
        self.label_38.setObjectName("label_38")
        self.label_39 = QtWidgets.QLabel(parent=self.detail)
        self.label_39.setGeometry(QtCore.QRect(630, 220, 381, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        self.label_39.setFont(font)
        self.label_39.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_39.setObjectName("label_39")
        self.label_40 = QtWidgets.QLabel(parent=self.detail)
        self.label_40.setGeometry(QtCore.QRect(630, 260, 351, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        self.label_40.setFont(font)
        self.label_40.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_40.setObjectName("label_40")
        self.label_41 = QtWidgets.QLabel(parent=self.detail)
        self.label_41.setGeometry(QtCore.QRect(630, 290, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        self.label_41.setFont(font)
        self.label_41.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_41.setObjectName("label_41")
        self.label_42 = QtWidgets.QLabel(parent=self.detail)
        self.label_42.setGeometry(QtCore.QRect(630, 320, 321, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        self.label_42.setFont(font)
        self.label_42.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_42.setObjectName("label_42")
        self.label_43 = QtWidgets.QLabel(parent=self.detail)
        self.label_43.setGeometry(QtCore.QRect(630, 360, 451, 61))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        self.label_43.setFont(font)
        self.label_43.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_43.setObjectName("label_43")
        self.label_44 = QtWidgets.QLabel(parent=self.detail)
        self.label_44.setGeometry(QtCore.QRect(630, 430, 261, 20))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        self.label_44.setFont(font)
        self.label_44.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_44.setObjectName("label_44")
        self.pushButton_8 = QtWidgets.QPushButton(parent=self.detail)
        self.pushButton_8.setGeometry(QtCore.QRect(932, 20, 111, 41))
        self.pushButton_8.setStyleSheet("border: none;\n"
"    background: transparent;")
        self.pushButton_8.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA09/TuanHy/python-app/ui/../img/backward-solid.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_8.setIcon(icon2)
        self.pushButton_8.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_8.setObjectName("pushButton_8")
        self.btn_booking = QtWidgets.QPushButton(parent=self.detail)
        self.btn_booking.setGeometry(QtCore.QRect(630, 500, 200, 50))
        self.btn_booking.setStyleSheet("QPushButton {\n"
"    background-color: #007A3D;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    padding: 10px 20px;\n"
"    font-weight: bold;\n"
"    font-size: 16px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #005a2e;\n"
"}")
        self.btn_booking.setObjectName("btn_booking")
        self.stackedWidget.addWidget(self.detail)

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_8.setText(_translate("Form", "WELCOME"))
        self.btn_home.setText(_translate("Form", "Home"))
        self.btn_profile.setText(_translate("Form", "Profile"))
        self.btn_list.setText(_translate("Form", "List"))
        self.lineEdit_2.setPlaceholderText(_translate("Form", "standard number of people on a football field"))
        self.label_3.setText(_translate("Form", "City"))
        self.lineEdit.setPlaceholderText(_translate("Form", "Enter Your City"))
        self.label_2.setText(_translate("Form", "BEST TURF BOOKING"))
        self.label_4.setText(_translate("Form", "Type"))
        self.label_9.setText(_translate("Form", "PLATFORM IN YOUR AREA"))
        self.label_7.setText(_translate("Form", "District"))
        self.lineEdit_3.setPlaceholderText(_translate("Form", "Enter Your District"))
        self.label_6.setText(_translate("Form", "Explore best tuft nearby you"))
        self.label_22.setText(_translate("Form", "Email"))
        self.label_23.setText(_translate("Form", "Gender"))
        self.label_24.setText(_translate("Form", "Birthday"))
        self.label_29.setText(_translate("Form", "Name"))
        self.btn_save_account.setText(_translate("Form", "Save"))
        self.txt_gender.setItemText(0, _translate("Form", "None"))
        self.txt_gender.setItemText(1, _translate("Form", "Male"))
        self.txt_gender.setItemText(2, _translate("Form", "Famale"))
        self.txt_gender.setItemText(3, _translate("Form", "Other"))
        self.label_39.setText(_translate("Form", "Tên : Sân Bóng Đá Mini Tân Thới Hoà"))
        self.label_40.setText(_translate("Form", "Địa Chỉ : 17 Lương Minh Nguyệt"))
        self.label_41.setText(_translate("Form", "Loại cỏ : Cỏ Nhân tạo"))
        self.label_42.setText(_translate("Form", "Loại sân: Sân Bóng đá 5 người"))
        self.label_43.setText(_translate("Form", "Loại bóng để đá : Tất cả các loại banh được \n"
" dùng trong bogs đá ưu tiên banh 2030"))
        self.label_44.setText(_translate("Form", "Liên Lạc : 0868 180 975 "))
        self.btn_booking.setText(_translate("Form", "Đặt Sân"))
