# Form implementation generated from reading ui file '/Users/pinxun/Documents/MindX/PTA/PTA09/TuanHy/python-app/ui/item.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.lb_name = QtWidgets.QLabel(parent=Form)
        self.lb_name.setGeometry(QtCore.QRect(130, 10, 111, 20))
        self.lb_name.setObjectName("lb_name")
        self.lb_image = QtWidgets.QLabel(parent=Form)
        self.lb_image.setGeometry(QtCore.QRect(60, 40, 261, 151))
        self.lb_image.setText("")
        self.lb_image.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA09/TuanHy/python-app/ui/../img/unnamed.webp"))
        self.lb_image.setScaledContents(True)
        self.lb_image.setObjectName("lb_image")
        self.lb_icon_star = QtWidgets.QLabel(parent=Form)
        self.lb_icon_star.setGeometry(QtCore.QRect(260, 200, 51, 41))
        self.lb_icon_star.setText("")
        self.lb_icon_star.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA09/TuanHy/python-app/ui/../img/star-solid.svg"))
        self.lb_icon_star.setScaledContents(True)
        self.lb_icon_star.setObjectName("lb_icon_star")
        self.lb_rating = QtWidgets.QLabel(parent=Form)
        self.lb_rating.setGeometry(QtCore.QRect(230, 220, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lb_rating.setFont(font)
        self.lb_rating.setObjectName("lb_rating")
        self.lb_price = QtWidgets.QLabel(parent=Form)
        self.lb_price.setGeometry(QtCore.QRect(220, 250, 121, 20))
        self.lb_price.setObjectName("lb_price")
        self.btn_detail = QtWidgets.QPushButton(parent=Form)
        self.btn_detail.setGeometry(QtCore.QRect(60, 210, 131, 31))
        self.btn_detail.setObjectName("btn_detail")
        self.btn_booking = QtWidgets.QPushButton(parent=Form)
        self.btn_booking.setGeometry(QtCore.QRect(60, 250, 131, 29))
        self.btn_booking.setObjectName("btn_booking")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lb_name.setText(_translate("Form", "Sân Gia Nguyễn"))
        self.lb_rating.setText(_translate("Form", "5/5"))
        self.lb_price.setText(_translate("Form", "200000VND/hour"))
        self.btn_detail.setText(_translate("Form", "Detail"))
        self.btn_booking.setText(_translate("Form", "Booking"))
