# Form implementation generated from reading ui file '/Users/pinxun/Documents/MindX/PTA/PTA09/TuanHy/python-app/ui/login.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 600)
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(-30, -20, 861, 621))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA09/TuanHy/python-app/ui/../img/OIP (1).jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setGeometry(QtCore.QRect(250, 10, 361, 551))
        self.label_2.setStyleSheet("background-color: rgba(255, 255, 255, 120);\n"
"border-radius: 15px;\n"
"")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=Form)
        self.label_3.setGeometry(QtCore.QRect(350, -120, 341, 401))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(20)
        font.setBold(False)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(0, 0, 0)")
        self.label_3.setObjectName("label_3")
        self.txt_email = QtWidgets.QLineEdit(parent=Form)
        self.txt_email.setGeometry(QtCore.QRect(270, 150, 301, 51))
        self.txt_email.setStyleSheet("border: 1px solid #ccc;\n"
"    border-radius: 20px;\n"
"    padding: 10px;\n"
"    background-color: white;\n"
"    font-size: 14px;\n"
"color: rgb(0, 0, 0)")
        self.txt_email.setText("")
        self.txt_email.setObjectName("txt_email")
        self.txt_password = QtWidgets.QLineEdit(parent=Form)
        self.txt_password.setGeometry(QtCore.QRect(270, 260, 291, 51))
        self.txt_password.setStyleSheet("border: 1px solid #ccc;\n"
"    border-radius: 20px;\n"
"    padding: 10px;\n"
"    background-color: white;\n"
"    font-size: 14px;\n"
"color: rgb(0, 0, 0)")
        self.txt_password.setText("")
        self.txt_password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.txt_password.setObjectName("txt_password")
        self.label_4 = QtWidgets.QLabel(parent=Form)
        self.label_4.setGeometry(QtCore.QRect(280, 110, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(0, 0, 0)")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=Form)
        self.label_5.setGeometry(QtCore.QRect(270, 220, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(0, 0, 0)")
        self.label_5.setObjectName("label_5")
        self.btn_login = QtWidgets.QPushButton(parent=Form)
        self.btn_login.setGeometry(QtCore.QRect(260, 380, 311, 51))
        self.btn_login.setStyleSheet("background-color: #8CD94D;  /* Màu xanh lá */\n"
"    border: none;\n"
"    border-radius: 20px;\n"
"    color: black;\n"
"    font-weight: bold;\n"
"    padding: 10px 20px;\n"
"    font-size: 14px;")
        self.btn_login.setObjectName("btn_login")
        self.checkBox = QtWidgets.QCheckBox(parent=Form)
        self.checkBox.setGeometry(QtCore.QRect(280, 330, 171, 26))
        font = QtGui.QFont()
        font.setBold(True)
        self.checkBox.setFont(font)
        self.checkBox.setStyleSheet("color: rgb(0, 0, 0)")
        self.checkBox.setObjectName("checkBox")
        self.btn_eye = QtWidgets.QPushButton(parent=Form)
        self.btn_eye.setGeometry(QtCore.QRect(490, 270, 83, 29))
        self.btn_eye.setStyleSheet("border: none;\n"
"    background: transparent;")
        self.btn_eye.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA09/TuanHy/python-app/ui/../img/eye-slash-solid.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_eye.setIcon(icon)
        self.btn_eye.setObjectName("btn_eye")
        self.pushButton_3 = QtWidgets.QPushButton(parent=Form)
        self.pushButton_3.setGeometry(QtCore.QRect(280, 350, 191, 29))
        self.pushButton_3.setStyleSheet("border: none;\n"
"    background: transparent;\n"
"color: rgb(0, 0, 0)")
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_6 = QtWidgets.QLabel(parent=Form)
        self.label_6.setGeometry(QtCore.QRect(280, 460, 181, 31))
        self.label_6.setObjectName("label_6")
        self.btn_register = QtWidgets.QPushButton(parent=Form)
        self.btn_register.setGeometry(QtCore.QRect(440, 460, 101, 29))
        self.btn_register.setStyleSheet("border: 1px solid rgba(0, 0, 0, 0);  /* Viền trong suốt */\n"
"color: rgb(85, 255, 0)\n"
"")
        self.btn_register.setObjectName("btn_register")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_3.setText(_translate("Form", "WELCOME"))
        self.txt_email.setPlaceholderText(_translate("Form", "Enter your email"))
        self.txt_password.setPlaceholderText(_translate("Form", "Enter your pasword"))
        self.label_4.setText(_translate("Form", "Email"))
        self.label_5.setText(_translate("Form", "Password"))
        self.btn_login.setText(_translate("Form", "Log in"))
        self.checkBox.setText(_translate("Form", "Stay log in in 30 days"))
        self.pushButton_3.setText(_translate("Form", "you forgot your password?"))
        self.label_6.setText(_translate("Form", "if you don\'t have account?"))
        self.btn_register.setText(_translate("Form", "Register"))
