# Form implementation generated from reading ui file '/Users/pinxun/Documents/MindX/PTA/PTA09/TuanHy/python-app/ui/register.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 600)
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(800, 600, 711, 451))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA09/TuanHy/python-app/ui/img/images (1).jpg"))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setGeometry(QtCore.QRect(30, 110, 63, 20))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=Form)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 821, 601))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA09/TuanHy/python-app/ui/../img/images (1).jpg"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=Form)
        self.label_4.setGeometry(QtCore.QRect(250, 0, 361, 591))
        self.label_4.setStyleSheet("background-color: rgba(255, 255, 255, 120);\n"
"border-radius: 15px;")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=Form)
        self.label_5.setGeometry(QtCore.QRect(280, 20, 311, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe Fluent Icons")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setStrikeOut(False)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(0, 0, 0)")
        self.label_5.setObjectName("label_5")
        self.txt_email = QtWidgets.QLineEdit(parent=Form)
        self.txt_email.setGeometry(QtCore.QRect(280, 160, 291, 51))
        self.txt_email.setStyleSheet("border: 1px solid #ccc;\n"
"    border-radius: 20px;\n"
"    padding: 10px;\n"
"    background-color: white;\n"
"    font-size: 14px;\n"
"color: rgb(0, 0, 0)")
        self.txt_email.setText("")
        self.txt_email.setObjectName("txt_email")
        self.txt_password = QtWidgets.QLineEdit(parent=Form)
        self.txt_password.setGeometry(QtCore.QRect(280, 230, 291, 51))
        self.txt_password.setStyleSheet("border: 1px solid #ccc;\n"
"    border-radius: 20px;\n"
"    padding: 10px;\n"
"    background-color: white;\n"
"    font-size: 14px;\n"
"color: rgb(0, 0, 0)")
        self.txt_password.setText("")
        self.txt_password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.txt_password.setObjectName("txt_password")
        self.btn_register = QtWidgets.QPushButton(parent=Form)
        self.btn_register.setGeometry(QtCore.QRect(280, 370, 291, 61))
        self.btn_register.setStyleSheet("background-color: #8CD94D;  /* Màu xanh lá */\n"
"    border: none;\n"
"    border-radius: 20px;\n"
"    color: black;\n"
"    font-weight: bold;\n"
"    padding: 10px 20px;\n"
"    font-size: 14px;")
        self.btn_register.setObjectName("btn_register")
        self.label_7 = QtWidgets.QLabel(parent=Form)
        self.label_7.setGeometry(QtCore.QRect(130, 60, 63, 20))
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.txt_name = QtWidgets.QLineEdit(parent=Form)
        self.txt_name.setGeometry(QtCore.QRect(280, 90, 291, 51))
        self.txt_name.setStyleSheet("border: 1px solid #ccc;\n"
"    border-radius: 20px;\n"
"    padding: 10px;\n"
"    background-color: white;\n"
"    font-size: 14px;\n"
"color: rgb(0, 0, 0)")
        self.txt_name.setText("")
        self.txt_name.setObjectName("txt_name")
        self.txt_confirm_password = QtWidgets.QLineEdit(parent=Form)
        self.txt_confirm_password.setGeometry(QtCore.QRect(280, 300, 291, 51))
        self.txt_confirm_password.setStyleSheet("border: 1px solid #ccc;\n"
"    border-radius: 20px;\n"
"    padding: 10px;\n"
"    background-color: white;\n"
"    font-size: 14px;\n"
"color: rgb(0, 0, 0)")
        self.txt_confirm_password.setText("")
        self.txt_confirm_password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.txt_confirm_password.setObjectName("txt_confirm_password")
        self.btn_eye_p = QtWidgets.QPushButton(parent=Form)
        self.btn_eye_p.setGeometry(QtCore.QRect(480, 240, 83, 29))
        self.btn_eye_p.setStyleSheet("border: none;\n"
"    background: transparent;")
        self.btn_eye_p.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA09/TuanHy/python-app/ui/../img/eye-slash-solid.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_eye_p.setIcon(icon)
        self.btn_eye_p.setObjectName("btn_eye_p")
        self.btn_eye_cp = QtWidgets.QPushButton(parent=Form)
        self.btn_eye_cp.setGeometry(QtCore.QRect(480, 310, 83, 29))
        self.btn_eye_cp.setStyleSheet("border: none;\n"
"    background: transparent;")
        self.btn_eye_cp.setText("")
        self.btn_eye_cp.setIcon(icon)
        self.btn_eye_cp.setObjectName("btn_eye_cp")
        self.label_6 = QtWidgets.QLabel(parent=Form)
        self.label_6.setGeometry(QtCore.QRect(300, 450, 191, 41))
        self.label_6.setObjectName("label_6")
        self.btn_login = QtWidgets.QPushButton(parent=Form)
        self.btn_login.setGeometry(QtCore.QRect(500, 448, 83, 41))
        self.btn_login.setStyleSheet("border: 1px solid rgba(0, 0, 0, 0);  /* Viền trong suốt */\n"
"color: rgb(0, 255, 0)\n"
"")
        self.btn_login.setObjectName("btn_login")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_5.setText(_translate("Form", "CREATE ACCOUNT"))
        self.txt_email.setPlaceholderText(_translate("Form", "Email"))
        self.txt_password.setPlaceholderText(_translate("Form", "Password"))
        self.btn_register.setText(_translate("Form", "Register"))
        self.txt_name.setPlaceholderText(_translate("Form", "Name"))
        self.txt_confirm_password.setPlaceholderText(_translate("Form", "Comfirm Password"))
        self.label_6.setText(_translate("Form", "If you already have account"))
        self.btn_login.setText(_translate("Form", "Login"))
